# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fastening Products Co
email: fpc.inc@fastprodco.com
description: "Fastening Products Co., Inc. was established in 1971. We are located in Delaware County, PA, housed in our own 17,000 square foot facility."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.fastprodco.com/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
main_site_url: "http://www.fastprodco.com/"
kickinespresso_url: "https://www.kickinespresso.com"

# Build settings
markdown: kramdown
